### ISSUE TITLE
SyntaxError upon test

### ISSUE THREAD

**Issue by chartgerink** [jimpick/subscribed-hypercored#2]
I just tried to run `subscribed-hypercored` but keep getting this SyntaxError. I am running in bash on Fedora 26, `FEED_KEY` is available and the folder on the Dat network with only a `feeds` file. Any idea why this might be happening? 

```bash
/home/chjh/.npm-global/lib/node_modules/subscribed-hypercored/index.js:36
async function run () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

I made sure to export the `FEED_KEY` and was able to retrieve it from within node with `process.env.FEED_KEY`. Super excited about `subscribed-hypercored` so hope to test it out soon :bulb:

**Comment by jimpick** [comment]
I think you just need to use a newer version of node.js that has support for the async/await keywords.

**Comment by chartgerink** [comment]
Oh my I keep embarrassing myself! Solves it indeed.
